<?php
/**
 * @file
 * Stores entity_legal document published version info in state rather than config entity.
 */

use Drupal\entity_legal\EntityLegalDocumentInterface;

/**
 * Implements hook_entity_legal_published_version_alter().
 */
function entity_legal_state_entity_legal_published_version_alter(&$published_version_name, EntityLegalDocumentInterface $legal_document) {
  $published_version_name = \Drupal::service('entity_legal_state')->getPublishedVersion($legal_document, $published_version_name);
}
